name: Reusable Workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: name of uploaded artifact
                required: false
                default: dist
                type: string
        outputs:
            result:
              description: output of deploying app
              value: ${{ jobs.deploy.outputs.output-value }}

        # secrets:
        #     some-secret:
        #         required: false

jobs:
    deploy:
        outputs:
            output-value: ${{ steps.output-step.outputs.value }}
        runs-on: ubuntu-latest
        steps:
        - name: Get build artifacts
          uses: actions/download-artifact@v3
          with:
            name: dist-files
        - name: Output contents
          run: ls
        - name: Deploy
          id: output-step
          run: echo "value=Deploying..." >> $GITHUB_OUTPUT